### ISSUE TITLE
Contributor README Emails

### ISSUE THREAD

**Issue by tbrlpld** [snek-shipyard/wagtail-bifrost#1]
Hi, 

I keep getting emails with this subject line `[snek-shipyard/wagtail-bifrost] Add contributors to README.md (#102) (e12ea7c)`. 

I do not know what this package here is all about, but could you just remove the contributor file from this package? This is not the sort of thing I want to keep getting emails about. 

I wonder if this keeps happening because you merge in Grapple or doing rebases. 

Thank you.

**Comment by longwand** [comment]
That should no longer be the case. Sorry for disturbance. Feel free to contact me if you get emails again.

**Comment by tbrlpld** [comment]
👌 Thank you
